import Actions from "./Actions"
import Attributes from "./Attributes"
import Brand from "./Brand"
import Branding from "./Branding"
import Details from "./Details"
import FixedActions from "./FixedActions"
import Gallery from "./Gallery"
import ImageModalGalleries from "./ImageModalGalleries"
import Layout from "./Layout"
import MoreDetails from "./MoreDetails"
import PricesDrawer from "./PricesDrawer"
import QuestionForm from "./QuestionForm"
import Questions from "./Questions"
import RelatedProducts from "./RelatedProducts"
import Reviews from "./Reviews"
import Summary from "./Summary"
import Tabs from "./Tabs"
import TopFixedActions from "./TopFixedActions"
import VariantAttributes from "./VariantAttributes"

export { Actions }
export { Attributes }
export { Brand }
export { Branding }
export { Details }
export { FixedActions }
export { Gallery }
export { ImageModalGalleries }
export { Layout }
export { MoreDetails }
export { PricesDrawer }
export { QuestionForm }
export { Questions }
export { RelatedProducts }
export { Reviews }
export { Summary }
export { Tabs }
export { TopFixedActions }
export { VariantAttributes }
