import ArrowDown from "./ArrowDown"
import ArrowLeft from "./ArrowLeft"
import ArrowLeftFill from "./ArrowLeftFill"
import ArrowRight from "./ArrowRight"
import ArrowRightFill from "./ArrowRightFill"
import Basket from "./Basket"
import Calendar from "./Calendar"
import Category from "./Category"
import Chat from "./Chat"
import Checked from "./Checked"
import CheckedIcon from "./CheckedIcon"
import Close from "./Close"
import Delivery from "./Delivery"
import EditIcon from "./EditIcon"
import Eye from "./Eye"
import Home from "./Home"
import Loading from "./Loading"
import Magnifier from "./Magnifier"
import MagnifierWithPlus from "./MagnifierWithPlus"
import Minus from "./Minus"
import NavigateNext from "./NavigateNext"
import NavigatePrev from "./NavigatePrev"
import Person from "./Person"
import Plus from "./Plus"
import Question from "./Question"
import Remove from "./Remove"
import Star from "./Star"
import Tag from "./Tag"
import Text from "./Text"
import ThreeLine from "./ThreeLine"
import UserIcon from "./UserIcon"
import VideoIcon from "./VideoIcon"

export { ArrowDown }
export { ArrowLeft }
export { ArrowLeftFill }
export { ArrowRight }
export { ArrowRightFill }
export { Basket }
export { Calendar }
export { Category }
export { Chat }
export { Checked }
export { CheckedIcon }
export { Close }
export { Delivery }
export { EditIcon }
export { Eye }
export { Home }
export { Loading }
export { Magnifier }
export { MagnifierWithPlus }
export { Minus }
export { NavigateNext }
export { NavigatePrev }
export { Person }
export { Plus }
export { Question }
export { Remove }
export { Star }
export { Tag }
export { Text }
export { ThreeLine }
export { UserIcon }
export { VideoIcon }
